name: PridePvP Games
main: com.pridemc.games.Core
version: 1.0
depend: [HawkEye]
commands:
    arena:
        description: Handles all Arena-based commands
        usage: /arena [args]
    pg:
        description: Handles all Player-based commands
        usage: /pg [args]
    class:
        description: Handles all Class-based commands
        usage: /class [args]