name: PridePvP Games
main: com.pridemc.games.Core
version: 1.0
commands:
    arena:
        description: Handles all Arena-based commands
        usage: /arena [args]
    pga:
        description: Handles all admin commands
        usage: /pga [args]